local:
  dialect: postgres
  datasource: host=localhost port=25431 dbname=caixa user=caixa password=QaCBG@NAet^7uANRzDD+y!Zbyy6rWJaE sslmode=disable
  dir: internal/migrations
  table: migrations

development:
  dialect: postgres
  datasource: host=${DB_HOST} port=${PORT} dbname=${DB_NAME} user=${DB_USER} password=${DB_PASSWORD} sslmode=${DB_SSLMODE}
  dir: internal/migrations
  table: migrations

production:
  dialect: postgres
  datasource: host=${DB_HOST} port=${PORT} dbname=${DB_NAME} user=${DB_USER} password=${DB_PASSWORD} sslmode=${DB_SSLMODE}
  dir: internal/migrations
  table: migrations
