# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Database Migrations

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Which environment you'd like to run the migrations
        options:
          - development
          - production
      migrate:
        type: choice
        description: What kind of migration want to run
        options:
        - up
        - down

env:
  DB_HOST: ${{ secrets.DB_HOST_DEV }}
  DB_PORT: ${{ secrets.DB_PORT_DEV }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD_DEV }}
  DB_NAME: bifrost
  DB_USER: bifrost
  DB_SSLMODE: disable

jobs:
  migrations:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Install Go sql-migrate
      run: go install github.com/rubenv/sql-migrate/...@latest
      
    - name: Run Migrations
      run: sql-migrate ${{ github.event.inputs.migrate }} -config=internal/config/dbconfig.yml -env={{ github.event.inputs.environment }}
