# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Development Migration Down

on: workflow_dispatch

env:
  DB_HOST: ${{ secrets.DB_HOST_DEV }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD_DEV }}
  DB_NAME: caixa
  DB_USER: caixa
  DB_SSLMODE: disable

jobs:
  migrations:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Install Go sql-migrate
      run: go install github.com/rubenv/sql-migrate/...@latest
      
    - name: Run Migrate Down
      run: sql-migrate down -config=internal/config/dbconfig.yml -env=remote
